//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaWSIZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AwariaBlacharska
    {
        public int id { get; set; }
        public int id_samochod { get; set; }
        [Required]
        public System.DateTime dataAwarii { get; set; }
        [Required]
        public double cena { get; set; }
        public string zdarzenie { get; set; }
    
        public virtual Samochody Samochody { get; set; }
    }
}
