//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaWSIZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CzynnosciAutoCoDotyczy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CzynnosciAutoCoDotyczy()
        {
            this.CzynnosciWykonane = new HashSet<CzynnosciWykonane>();
        }
    
        public int id { get; set; }
        public int id_samochod { get; set; }
        [Required]
        public Nullable<int> czynnoscKM { get; set; }
        [Required]
        public Nullable<int> czynnoscMiesiace { get; set; }
        [Required]
        public string nazwaCzynnosci { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CzynnosciWykonane> CzynnosciWykonane { get; set; }
        public virtual Samochody Samochody { get; set; }
    }
}
