//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaWSIZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CzynnosciWykonane
    {
        public int id { get; set; }
        public int id_czynnosc { get; set; }
        [Required]
        public Nullable<int> stanKm { get; set; }
        [Required]
        public Nullable<System.DateTime> stanData { get; set; }
        [Required]
        public Nullable<double> cena { get; set; }
        [Required]
        public string opis { get; set; }
    
        public virtual CzynnosciAutoCoDotyczy CzynnosciAutoCoDotyczy { get; set; }
    }
}
