//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaWSIZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.AwariaBlacharska = new HashSet<AwariaBlacharska>();
            this.AwariaMechaniczna = new HashSet<AwariaMechaniczna>();
            this.CzynnosciAutoCoDotyczy = new HashSet<CzynnosciAutoCoDotyczy>();
            this.Sprzedane = new HashSet<Sprzedane>();
            this.Tankowanie = new HashSet<Tankowanie>();
            this.Zdarzenie = new HashSet<Zdarzenie>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage ="Brak marki")]
        public string marka { get; set; }
        [Required(ErrorMessage ="Brak modelu")]
        public string model { get; set; }
        [Required(ErrorMessage ="Brak rodzaju nadwozia")]
        public string nazwozie { get; set; }
        [Required(ErrorMessage = "Brak rodzaju paliwa")]
        public string paliwo { get; set; }
        [Required(ErrorMessage = "Brak mocy silnika")]
        [Range(1,1000)]
        public int konie { get; set; }
        [Required(ErrorMessage = "Brak pojemnoœci silnika")]
        [Range(1,100)]
        public double pojemnosc { get; set; }
        [Required(ErrorMessage = "Brak numeru rejestracyjnego")]
        public string nrRejestracyjny { get; set; }
        [Required(ErrorMessage = "Brak roku produkcji")]
        [Range(1900,3000)]
        public int rokProd { get; set; }
        [Required(ErrorMessage = "Brak daty pierwszej rejestracji")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dataRejestracji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AwariaBlacharska> AwariaBlacharska { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AwariaMechaniczna> AwariaMechaniczna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CzynnosciAutoCoDotyczy> CzynnosciAutoCoDotyczy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedane> Sprzedane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tankowanie> Tankowanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdarzenie> Zdarzenie { get; set; }
    }
}
