//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaWSIZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedane
    {
        public int id { get; set; }
        public int id_samochod { get; set; }
        public bool sprzedane1 { get; set; }
    
        public virtual Samochody Samochody { get; set; }
    }
}
