//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracaWSIZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tankowanie
    {
        public int id { get; set; }

        [Required(ErrorMessage ="brak iloœci paliwa")]
        public double litry { get; set; }

        [Required(ErrorMessage = "brak stanu kilometrów")]
        public int Km { get; set; }

        [Required(ErrorMessage ="Brak ceny")]
        public double cena { get; set; }

        public int id_samochod { get; set; }

        public virtual Samochody Samochody { get; set; }
    }
}
